//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DxfOpener.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DxfOpener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        public static string dialogAboutProduct {
            get {
                return ResourceManager.GetString("dialogAboutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What to do with dots?.
        /// </summary>
        public static string dialogActWithPoints {
            get {
                return ResourceManager.GetString("dialogActWithPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string dialogButtonCancel {
            get {
                return ResourceManager.GetString("dialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string dialogButtonCreate {
            get {
                return ResourceManager.GetString("dialogButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify.
        /// </summary>
        public static string dialogButtonModify {
            get {
                return ResourceManager.GetString("dialogButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string dialogButtonOk {
            get {
                return ResourceManager.GetString("dialogButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string dialogButtonRun {
            get {
                return ResourceManager.GetString("dialogButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer name:.
        /// </summary>
        public static string dialogComputerName {
            get {
                return ResourceManager.GetString("dialogComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify polylines.
        /// </summary>
        public static string dialogConvertPolyline {
            get {
                return ResourceManager.GetString("dialogConvertPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на remove all.
        /// </summary>
        public static string dialogDeleteAll {
            get {
                return ResourceManager.GetString("dialogDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program opens and modifies DXF files..
        /// </summary>
        public static string dialogDescription {
            get {
                return ResourceManager.GetString("dialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify ellipses.
        /// </summary>
        public static string dialogEllipses {
            get {
                return ResourceManager.GetString("dialogEllipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The document {0} {1} {2}.
        /// </summary>
        public static string dialogFoundPoints {
            get {
                return ResourceManager.GetString("dialogFoundPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains.
        /// </summary>
        public static string dialogFoundPointsContains_1 {
            get {
                return ResourceManager.GetString("dialogFoundPointsContains_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на contains.
        /// </summary>
        public static string dialogFoundPointsContains_2 {
            get {
                return ResourceManager.GetString("dialogFoundPointsContains_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skip all objetcs.
        /// </summary>
        public static string dialogIgnoreOtherLine {
            get {
                return ResourceManager.GetString("dialogIgnoreOtherLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create LWPOLYLINE.
        /// </summary>
        public static string dialogLWPolyline {
            get {
                return ResourceManager.GetString("dialogLWPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Marking.
        /// </summary>
        public static string dialogMarkup {
            get {
                return ResourceManager.GetString("dialogMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move all to the origin.
        /// </summary>
        public static string dialogMoveToZero {
            get {
                return ResourceManager.GetString("dialogMoveToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name:.
        /// </summary>
        public static string dialogNameProfile {
            get {
                return ResourceManager.GetString("dialogNameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not closed shape.
        /// </summary>
        public static string dialogOpenContour {
            get {
                return ResourceManager.GetString("dialogOpenContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Precision:.
        /// </summary>
        public static string dialogPrecision {
            get {
                return ResourceManager.GetString("dialogPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Program:.
        /// </summary>
        public static string dialogProduct {
            get {
                return ResourceManager.GetString("dialogProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dxf Reader.
        /// </summary>
        public static string dialogProductName {
            get {
                return ResourceManager.GetString("dialogProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version:.
        /// </summary>
        public static string dialogProductVersion {
            get {
                return ResourceManager.GetString("dialogProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.1.0.0.
        /// </summary>
        public static string dialogProductVersionNumber {
            get {
                return ResourceManager.GetString("dialogProductVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create R13.
        /// </summary>
        public static string dialogR13 {
            get {
                return ResourceManager.GetString("dialogR13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save the file for the changes to take effect.
        /// </summary>
        public static string dialogSaveFile {
            get {
                return ResourceManager.GetString("dialogSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mark as:.
        /// </summary>
        public static string dialogSelectAs {
            get {
                return ResourceManager.GetString("dialogSelectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на point..
        /// </summary>
        public static string dialogStringPoint {
            get {
                return ResourceManager.GetString("dialogStringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points..
        /// </summary>
        public static string dialogStringPoints {
            get {
                return ResourceManager.GetString("dialogStringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на points..
        /// </summary>
        public static string dialogStringPoints2 {
            get {
                return ResourceManager.GetString("dialogStringPoints2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About system.
        /// </summary>
        public static string dialogSystemInfo {
            get {
                return ResourceManager.GetString("dialogSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на System:.
        /// </summary>
        public static string dialogSystemName {
            get {
                return ResourceManager.GetString("dialogSystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Dxf Reader v2.1 program.
        /// </summary>
        public static string dialogTitleAbout {
            get {
                return ResourceManager.GetString("dialogTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the {0} profile.
        /// </summary>
        public static string dialogTitleModify {
            get {
                return ResourceManager.GetString("dialogTitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing points.
        /// </summary>
        public static string dialogTitleModifyPoints {
            get {
                return ResourceManager.GetString("dialogTitleModifyPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation a new profile.
        /// </summary>
        public static string dialogTitleNew {
            get {
                return ResourceManager.GetString("dialogTitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing of the {0} profile.
        /// </summary>
        public static string dialogTitleView {
            get {
                return ResourceManager.GetString("dialogTitleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If a polyline contains bulges, it will be broken down into simpler entities.
        /// </summary>
        public static string dialogTooltipConvertPolyline {
            get {
                return ResourceManager.GetString("dialogTooltipConvertPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the document contains Elliptical Arc, it will be converted to a polyline.
        /// </summary>
        public static string dialogTooltipEllipses {
            get {
                return ResourceManager.GetString("dialogTooltipEllipses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the entities are not a primary line, a marking, or a non-closed shape, they will be added to the document.
        /// </summary>
        public static string dialogTooltipIgnoreOtherLine {
            get {
                return ResourceManager.GetString("dialogTooltipIgnoreOtherLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Such a polyline takes up less disk space.
        /// </summary>
        public static string dialogTooltipLWPolyline {
            get {
                return ResourceManager.GetString("dialogTooltipLWPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move everythink to the origin.
        /// </summary>
        public static string dialogTooltipMoveToZero {
            get {
                return ResourceManager.GetString("dialogTooltipMoveToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a document AC2012 version.
        /// </summary>
        public static string dialogTooltipR13 {
            get {
                return ResourceManager.GetString("dialogTooltipR13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User:.
        /// </summary>
        public static string dialogUser {
            get {
                return ResourceManager.GetString("dialogUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done. Total strings: {0}.
        /// </summary>
        public static string docCreated {
            get {
                return ResourceManager.GetString("docCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Document not created.
        /// </summary>
        public static string docNotCreated {
            get {
                return ResourceManager.GetString("docNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DxfReader.chm.
        /// </summary>
        public static string helpFileName {
            get {
                return ResourceManager.GetString("helpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program.
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove the profile….
        /// </summary>
        public static string menuDeleteProfile {
            get {
                return ResourceManager.GetString("menuDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Edit.
        /// </summary>
        public static string menuEdit {
            get {
                return ResourceManager.GetString("menuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit current profile.
        /// </summary>
        public static string menuEditProfile {
            get {
                return ResourceManager.GetString("menuEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Help.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help Contents.
        /// </summary>
        public static string menuHelpContents {
            get {
                return ResourceManager.GetString("menuHelpContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Open all files in the current window.
        /// </summary>
        public static string menuOnlyOneWindow {
            get {
                return ResourceManager.GetString("menuOnlyOneWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open....
        /// </summary>
        public static string menuOpen {
            get {
                return ResourceManager.GetString("menuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit or delete points....
        /// </summary>
        public static string menuPoints {
            get {
                return ResourceManager.GetString("menuPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print....
        /// </summary>
        public static string menuPrint {
            get {
                return ResourceManager.GetString("menuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Profile.
        /// </summary>
        public static string menuProfile {
            get {
                return ResourceManager.GetString("menuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string menuRefresh {
            get {
                return ResourceManager.GetString("menuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string menuSave {
            get {
                return ResourceManager.GetString("menuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as....
        /// </summary>
        public static string menuSaveAs {
            get {
                return ResourceManager.GetString("menuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select profile.
        /// </summary>
        public static string menuSelectProfile {
            get {
                return ResourceManager.GetString("menuSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show menu bar.
        /// </summary>
        public static string menuShowMenu {
            get {
                return ResourceManager.GetString("menuShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show status bar.
        /// </summary>
        public static string menuShowStatusBar {
            get {
                return ResourceManager.GetString("menuShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show text.
        /// </summary>
        public static string menuShowText {
            get {
                return ResourceManager.GetString("menuShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show tool bar.
        /// </summary>
        public static string menuShowToolBar {
            get {
                return ResourceManager.GetString("menuShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show image.
        /// </summary>
        public static string menuShowVisual {
            get {
                return ResourceManager.GetString("menuShowVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify splines.
        /// </summary>
        public static string menuSpline {
            get {
                return ResourceManager.GetString("menuSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _View.
        /// </summary>
        public static string menuView {
            get {
                return ResourceManager.GetString("menuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View permanent profile.
        /// </summary>
        public static string menuViewProfile {
            get {
                return ResourceManager.GetString("menuViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating profile error.
        /// </summary>
        public static string msgCreateProfErrorTitle {
            get {
                return ResourceManager.GetString("msgCreateProfErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string msgErrorTitle {
            get {
                return ResourceManager.GetString("msgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This file is not a DXF file.
        /// </summary>
        public static string msgNotDxf {
            get {
                return ResourceManager.GetString("msgNotDxf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File {0} has not been saved. Do you want to save it before you open a new one?.
        /// </summary>
        public static string msgNotSaveFile {
            get {
                return ResourceManager.GetString("msgNotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string msgOpenFileErrorTitle {
            get {
                return ResourceManager.GetString("msgOpenFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path not found.
        /// </summary>
        public static string msgPathNotFind {
            get {
                return ResourceManager.GetString("msgPathNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The document was not created..
        /// </summary>
        public static string msgPrintError {
            get {
                return ResourceManager.GetString("msgPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string msgPrintErrorTitle {
            get {
                return ResourceManager.GetString("msgPrintErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete the profile &apos;{0} &apos;?.
        /// </summary>
        public static string msgProfileDelete {
            get {
                return ResourceManager.GetString("msgProfileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile deleting.
        /// </summary>
        public static string msgProfileDelTitle {
            get {
                return ResourceManager.GetString("msgProfileDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile name cannot be empty.
        /// </summary>
        public static string msgProfNameEmpty {
            get {
                return ResourceManager.GetString("msgProfNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving changes.
        /// </summary>
        public static string msgSavaModFileTitle {
            get {
                return ResourceManager.GetString("msgSavaModFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving file.
        /// </summary>
        public static string msgSaveFileTitle {
            get {
                return ResourceManager.GetString("msgSaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file has been changed, save the changes?.
        /// </summary>
        public static string msgSaveModifiedFile {
            get {
                return ResourceManager.GetString("msgSaveModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string msgSaveProfErrorTitle {
            get {
                return ResourceManager.GetString("msgSaveProfErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The precision cannot be less 2.
        /// </summary>
        public static string msgSmallPrecision {
            get {
                return ResourceManager.GetString("msgSmallPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error writing file {0}.
        /// </summary>
        public static string msgWritingFileErrorTitle {
            get {
                return ResourceManager.GetString("msgWritingFileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout waiting for exclusive access.
        /// </summary>
        public static string mutexTimeout {
            get {
                return ResourceManager.GetString("mutexTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No objects.
        /// </summary>
        public static string NoObjects {
            get {
                return ResourceManager.GetString("NoObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Objects count:.
        /// </summary>
        public static string objectsCount {
            get {
                return ResourceManager.GetString("objectsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DXF AutoCad files|*.dxf.
        /// </summary>
        public static string openDialogFilters {
            get {
                return ResourceManager.GetString("openDialogFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string profileBase_1 {
            get {
                return ResourceManager.GetString("profileBase_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AJAN.
        /// </summary>
        public static string profileBase_2 {
            get {
                return ResourceManager.GetString("profileBase_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AC1012.
        /// </summary>
        public static string profileBase_3 {
            get {
                return ResourceManager.GetString("profileBase_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] RT_MANIFEST {
            get {
                object obj = ResourceManager.GetObject("RT_MANIFEST", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width: {0} mm; Height: {1} mm.
        /// </summary>
        public static string sizeToString {
            get {
                return ResourceManager.GetString("sizeToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time: {0} sec..
        /// </summary>
        public static string timeText {
            get {
                return ResourceManager.GetString("timeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DXF Reader.
        /// </summary>
        public static string titleMainWindow {
            get {
                return ResourceManager.GetString("titleMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help Contents (F1).
        /// </summary>
        public static string tooltipAbout {
            get {
                return ResourceManager.GetString("tooltipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete current profile (Del).
        /// </summary>
        public static string tooltipDelProfile {
            get {
                return ResourceManager.GetString("tooltipDelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit current profile (Ctrl+R).
        /// </summary>
        public static string tooltipEditProfile {
            get {
                return ResourceManager.GetString("tooltipEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit (Alt+X или Esc).
        /// </summary>
        public static string tooltipExit {
            get {
                return ResourceManager.GetString("tooltipExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a new profile (Ctrl+N).
        /// </summary>
        public static string tooltipNewProfile {
            get {
                return ResourceManager.GetString("tooltipNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open DXF file and view it (Ctrl+O).
        /// </summary>
        public static string tooltipOpenFile {
            get {
                return ResourceManager.GetString("tooltipOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete or change points (Ctrl+.).
        /// </summary>
        public static string tooltipPoints {
            get {
                return ResourceManager.GetString("tooltipPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The precision with which you want to convert splines into polylines.
        /// </summary>
        public static string tooltipPrecisionBySpline {
            get {
                return ResourceManager.GetString("tooltipPrecisionBySpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pint the image (Ctrl+P).
        /// </summary>
        public static string tooltipPrint {
            get {
                return ResourceManager.GetString("tooltipPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload file (F5).
        /// </summary>
        public static string tooltipReloadFile {
            get {
                return ResourceManager.GetString("tooltipReloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save file (Ctrl+S).
        /// </summary>
        public static string tooltipSaveFile {
            get {
                return ResourceManager.GetString("tooltipSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify splines to polylines (F2).
        /// </summary>
        public static string tooltipSpline {
            get {
                return ResourceManager.GetString("tooltipSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View permanent profile (F6).
        /// </summary>
        public static string tooltipViewProfile {
            get {
                return ResourceManager.GetString("tooltipViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/dialogs/about.htm.
        /// </summary>
        public static string topicAboutDialog {
            get {
                return ResourceManager.GetString("topicAboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/profiles/custom.htm.
        /// </summary>
        public static string topicCustom {
            get {
                return ResourceManager.GetString("topicCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/dialogs/index.htm.
        /// </summary>
        public static string topicDialogs {
            get {
                return ResourceManager.GetString("topicDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на general/dxf.htm.
        /// </summary>
        public static string topicDxf {
            get {
                return ResourceManager.GetString("topicDxf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на general/about.htm.
        /// </summary>
        public static string topicGenAbout {
            get {
                return ResourceManager.GetString("topicGenAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на general/index.htm.
        /// </summary>
        public static string topicGeneral {
            get {
                return ResourceManager.GetString("topicGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/index.htm.
        /// </summary>
        public static string topicGuid {
            get {
                return ResourceManager.GetString("topicGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/profiles/info.htm.
        /// </summary>
        public static string topicInfo {
            get {
                return ResourceManager.GetString("topicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/profiles/inner.htm.
        /// </summary>
        public static string topicInner {
            get {
                return ResourceManager.GetString("topicInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/index.htm.
        /// </summary>
        public static string topicInterface {
            get {
                return ResourceManager.GetString("topicInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/menu.htm.
        /// </summary>
        public static string topicMenu {
            get {
                return ResourceManager.GetString("topicMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/dialogs/points.htm.
        /// </summary>
        public static string topicPoinsDialog {
            get {
                return ResourceManager.GetString("topicPoinsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/dialogs/profile.htm.
        /// </summary>
        public static string topicProfDialog {
            get {
                return ResourceManager.GetString("topicProfDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/profiles/index.htm.
        /// </summary>
        public static string topicProfiles {
            get {
                return ResourceManager.GetString("topicProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на start.htm.
        /// </summary>
        public static string topicStart {
            get {
                return ResourceManager.GetString("topicStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/status.htm.
        /// </summary>
        public static string topicStatus {
            get {
                return ResourceManager.GetString("topicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/text.htm.
        /// </summary>
        public static string topicText {
            get {
                return ResourceManager.GetString("topicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/toolbar.htm.
        /// </summary>
        public static string topicToolbar {
            get {
                return ResourceManager.GetString("topicToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на guid/interface/visual.htm.
        /// </summary>
        public static string topicVisual {
            get {
                return ResourceManager.GetString("topicVisual", resourceCulture);
            }
        }
    }
}
